- name: Deploy applications via ArgoCD
  hosts: control_plane
  become: true

  vars:
    kubeconfig_path: /home/ubuntu/.kube/config

  tasks:

    - name: Copy nginx ArgoCD application manifest
      copy:
        src: ../../k8s-manifests/argocd/nginx-app.yaml
        dest: /home/ubuntu/nginx-app.yaml

    - name: Apply nginx ArgoCD application
      become_user: ubuntu
      command: >
        kubectl apply -f /home/ubuntu/nginx-app.yaml
        --kubeconfig={{ kubeconfig_path }}