- hosts: control_plane
  become: true

  tasks:

    - name: Create kubeadm init configuration file
      copy:
        dest: /tmp/kubeadm-config.yaml
        content: |
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: ClusterConfiguration
          clusterName: k8s-cluster
          networking:
            podSubnet: 10.244.0.0/16
          ---
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: "aws"

    - name: Initialize cluster with config file
      shell: kubeadm init --config /tmp/kubeadm-config.yaml
      register: kubeadm_output
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Set join command fact
      set_fact:
        kube_join_cmd: "{{ join_command.stdout }}"

    - name: Create kube config directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Install CNI (Flannel)
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
