---
- hosts: control_plane
  gather_facts: false

  tasks:

    - name: Deploy nginx
      shell: kubectl create deployment nginx-demo --image=nginx
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      ignore_errors: true

    - name: Scale nginx
      shell: kubectl scale deployment nginx-demo --replicas=3
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Expose nginx via NodePort
      shell: kubectl expose deployment nginx-demo --type=NodePort --port=80
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      ignore_errors: true

    - name: Get NodePort
      shell: kubectl get svc nginx-demo -o jsonpath='{.spec.ports[0].nodePort}'
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      register: nodeport_output

    - name: Show access URL
      debug:
        msg: "Access the app at http://<worker-public-ip>:{{ nodeport_output.stdout }}"
