- hosts: workers
  become: true

  tasks:

    - name: Fail if join command is not available
      fail:
        msg: "Join command not found. Run the master playbook first."
      when: hostvars[groups['master'][0]].kube_join_cmd is not defined

    - name: Join Kubernetes cluster
      command: "{{ hostvars[groups['master'][0]].kube_join_cmd }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: join_result
    
    - debug:
        var: join_result.stdout